import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { ComponentClassNameMap } from '../phase-5-generate-class-names-map/generateClassNamesMap';

/**
 * Phase 6 - Persist build artifacts generated by previous phases
 * - Writes CSS to build/kiskadee.css
 * - Writes classNamesMap to build/classNamesMap.json
 */
export async function persistBuildArtifacts(
  cssGenerated: string,
  classNamesMap: ComponentClassNameMap,
  outDirName?: string
): Promise<void> {
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = dirname(__filename);

  // Ensure build dir exists
  const baseBuildDir = resolve(__dirname, '..', '..', 'build');
  const buildDir = outDirName ? resolve(baseBuildDir, outDirName) : baseBuildDir;
  await mkdir(buildDir, { recursive: true });

  // Persist CSS
  const outCssFile = resolve(buildDir, 'kiskadee.css');
  await writeFile(outCssFile, cssGenerated, 'utf8');
  console.log(`[web-builder] CSS written to: ${outCssFile}`);

  // Persist classNamesMap as JSON
  const classNamesOutFileJson = resolve(buildDir, 'classNamesMap.json');
  const classNamesJson = JSON.stringify(classNamesMap, null, 2);
  await writeFile(classNamesOutFileJson, classNamesJson, 'utf8');
  console.log(`[web-builder] ClassNames map written to: ${classNamesOutFileJson}`);
}
